# Generated by Django 4.2.20 on 2025-04-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='checado',
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato',
            field=models.IntegerField(default=0, verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='email_principal',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='Email Principal'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='email_secundario',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Secundário'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='medicos',
            field=models.CharField(default='Não especificado', max_length=255, verbose_name='Médicos'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='possui_acordo',
            field=models.BooleanField(default=False, verbose_name='Possui Acordo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(default='Ativo', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(default='Geral', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observacao',
            field=models.TextField(default='Sem observações', verbose_name='Observação'),
        ),
    ]
