# Generated by Django 4.2.20 on 2025-04-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_remove_contrato_checado_contrato_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='checado',
            field=models.BooleanField(default=False, verbose_name='Checado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='email_principal',
            field=models.EmailField(max_length=254, verbose_name='Email Principal'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='medicos',
            field=models.CharField(max_length=255, verbose_name='Médicos'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observacao',
            field=models.TextField(verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
