# Generated by Django 4.2.20 on 2025-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_checado_alter_contrato_email_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_ativacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_inativacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
